/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RedeemStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const RewardType = IDL.Variant({
  'amazon' : IDL.Null,
  'googlePlay' : IDL.Null,
});
export const RedeemRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : RedeemStatus,
  'date' : Time,
  'user' : IDL.Principal,
  'rewardType' : RewardType,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'nextAdWatchTime' : Time,
  'username' : IDL.Text,
  'coinBalance' : IDL.Nat,
  'dailyAdCount' : IDL.Nat,
});
export const Notice = IDL.Record({
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllRedeemRequests' : IDL.Func([], [IDL.Vec(RedeemRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoinBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getRedeemHistory' : IDL.Func([], [IDL.Vec(RedeemRequest)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'postNotice' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'recordAdWatch' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRedeemRequest' : IDL.Func([RewardType, IDL.Nat], [], []),
  'updateRedeemStatus' : IDL.Func([IDL.Nat, RedeemStatus], [], []),
  'updateUsername' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RedeemStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const RewardType = IDL.Variant({
    'amazon' : IDL.Null,
    'googlePlay' : IDL.Null,
  });
  const RedeemRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : RedeemStatus,
    'date' : Time,
    'user' : IDL.Principal,
    'rewardType' : RewardType,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'nextAdWatchTime' : Time,
    'username' : IDL.Text,
    'coinBalance' : IDL.Nat,
    'dailyAdCount' : IDL.Nat,
  });
  const Notice = IDL.Record({
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllRedeemRequests' : IDL.Func([], [IDL.Vec(RedeemRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoinBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getRedeemHistory' : IDL.Func([], [IDL.Vec(RedeemRequest)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'postNotice' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'recordAdWatch' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRedeemRequest' : IDL.Func([RewardType, IDL.Nat], [], []),
    'updateRedeemStatus' : IDL.Func([IDL.Nat, RedeemStatus], [], []),
    'updateUsername' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };