/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Notice {
  'title' : string,
  'date' : Time,
  'description' : string,
}
export interface RedeemRequest {
  'id' : bigint,
  'status' : RedeemStatus,
  'date' : Time,
  'user' : Principal,
  'rewardType' : RewardType,
  'amount' : bigint,
}
export type RedeemStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type RewardType = { 'amazon' : null } |
  { 'googlePlay' : null };
export type Time = bigint;
export interface UserProfile {
  'nextAdWatchTime' : Time,
  'username' : string,
  'coinBalance' : bigint,
  'dailyAdCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllRedeemRequests' : ActorMethod<[], Array<RedeemRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoinBalance' : ActorMethod<[], bigint>,
  'getNotices' : ActorMethod<[], Array<Notice>>,
  'getRedeemHistory' : ActorMethod<[], Array<RedeemRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRegistered' : ActorMethod<[], boolean>,
  'postNotice' : ActorMethod<[string, string], undefined>,
  'recordAdWatch' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRedeemRequest' : ActorMethod<[RewardType, bigint], undefined>,
  'updateRedeemStatus' : ActorMethod<[bigint, RedeemStatus], undefined>,
  'updateUsername' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];